#
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - entrypoint.sh
      - VERSION

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version from file
        run: |
          echo "VERSION=$(cat VERSION)" >> "$GITHUB_ENV"

      - name: Delete outdated tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          for tag in $(git tag); do
            echo $tag
            if [[ "${tag}" == "${VERSION}" ]]; then
              gh release delete $VERSION
              git tag --delete $VERSION
              git push --delete origin $VERSION
            fi
          done

      - name: Set up QEMU (for arm64 builds)
        uses: docker/setup-qemu-action@v2
  
      - name: Set up Docker Buildx (for multi-arch)
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Determine Container repository
        run: 'echo "CR_REPO=ghcr.io/${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}'

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          build-args: BW_CLI_VERSION=${{ env.VERSION }}
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: ${{ env.CR_REPO }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            const {VERSION} = process.env
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${VERSION}`,
              sha: context.sha
            })

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $VERSION -F VERSION
